In [1]:
d1 = {
    "key1":[1,2,3,4,5,"bhumik"],
    "key2":[7,8,9,10,11,12],
    "key3":[13,14,15,16,17,18],
    "key4":[19,20,21,22,23,24]
}   # all arrray must be of same length to convert to dataframe 

In [2]:
# converting dictionary to pandas dataframe :
import pandas as pd

pd.DataFrame(d1)

key1  key2  key3  key4
0       1     7    13    19
1       2     8    14    20
2       3     9    15    21
3       4    10    16    22
4       5    11    17    23
5  bhumik    12    18    24

In [3]:
# pd.DataFrame(d1,index =["a","b","c","d","e","f"])
df1 =  pd.DataFrame(d1)

In [4]:
d2 = {
    "key1":[1,2,3,4,5,"bhumik"],
    "key2":[7,8,"sawde",10,11,12],
    "key3":[13,14,15,16,17,18],
    "key4":[19,20,21,"ineuron","data_science",24]
} 

In [5]:
df2 = pd.DataFrame(d2)

In [6]:
df1

key1  key2  key3  key4
0       1     7    13    19
1       2     8    14    20
2       3     9    15    21
3       4    10    16    22
4       5    11    17    23
5  bhumik    12    18    24

In [7]:
df2

key1   key2  key3          key4
0       1      7    13            19
1       2      8    14            20
2       3  sawde    15            21
3       4     10    16       ineuron
4       5     11    17  data_science
5  bhumik     12    18            24

In [8]:
# Merge operation - 
#      (left,right)
pd.merge(df1,df2)  # by default, how = inner(intersection)

key1 key2  key3 key4
0       1    7    13   19
1       2    8    14   20
2  bhumik   12    18   24

In [9]:
pd.merge(df1,df2,how = "inner",on = "key1")

key1  key2_x  key3_x  key4_x key2_y  key3_y        key4_y
0       1       7      13      19      7      13            19
1       2       8      14      20      8      14            20
2       3       9      15      21  sawde      15            21
3       4      10      16      22     10      16       ineuron
4       5      11      17      23     11      17  data_science
5  bhumik      12      18      24     12      18            24

In [10]:
pd.merge(df1,df2,how = "inner",on = "key4")

key1_x  key2_x  key3_x key4  key1_y key2_y  key3_y
0       1       7      13   19       1      7      13
1       2       8      14   20       2      8      14
2       3       9      15   21       3  sawde      15
3  bhumik      12      18   24  bhumik     12      18

In [11]:
pd.merge(df1,df2,how = "left",on = "key4")  
# brings complete table from left and for right brings only those value which is common for key4

key1_x  key2_x  key3_x key4  key1_y key2_y  key3_y
0       1       7      13   19       1      7    13.0
1       2       8      14   20       2      8    14.0
2       3       9      15   21       3  sawde    15.0
3       4      10      16   22     NaN    NaN     NaN
4       5      11      17   23     NaN    NaN     NaN
5  bhumik      12      18   24  bhumik     12    18.0

In [12]:
pd.merge(df1,df2,how = "right",on = "key4")

key1_x  key2_x  key3_x          key4  key1_y key2_y  key3_y
0       1     7.0    13.0            19       1      7      13
1       2     8.0    14.0            20       2      8      14
2       3     9.0    15.0            21       3  sawde      15
3     NaN     NaN     NaN       ineuron       4     10      16
4     NaN     NaN     NaN  data_science       5     11      17
5  bhumik    12.0    18.0            24  bhumik     12      18

In [13]:
pd.merge(df1,df2,how = "outer",on = "key4") # complete merge operation

key1_x  key2_x  key3_x          key4  key1_y key2_y  key3_y
0       1     7.0    13.0            19       1      7    13.0
1       2     8.0    14.0            20       2      8    14.0
2       3     9.0    15.0            21       3  sawde    15.0
3       4    10.0    16.0            22     NaN    NaN     NaN
4       5    11.0    17.0            23     NaN    NaN     NaN
5  bhumik    12.0    18.0            24  bhumik     12    18.0
6     NaN     NaN     NaN       ineuron       4     10    16.0
7     NaN     NaN     NaN  data_science       5     11    17.0

In [14]:
pd.merge(df1,df2,how = "outer",on = ["key4","key1"]) 

key1  key2_x  key3_x          key4 key2_y  key3_y
0       1     7.0    13.0            19      7    13.0
1       2     8.0    14.0            20      8    14.0
2       3     9.0    15.0            21  sawde    15.0
3       4    10.0    16.0            22    NaN     NaN
4       5    11.0    17.0            23    NaN     NaN
5  bhumik    12.0    18.0            24     12    18.0
6       4     NaN     NaN       ineuron     10    16.0
7       5     NaN     NaN  data_science     11    17.0

In [15]:
d11 = {
    "a":[1,2,3,4,5,"bhumik"],
    "b":[7,8,9,10,11,12],
    "c":[13,14,15,16,17,18],
    "d":[19,20,21,22,23,24]
} 

In [16]:
d12 = {
    "key1":[1,2,3,4,5,"bhumik"],
    "key2":[7,8,"sawde",10,11,12],
    "key3":[13,14,15,16,17,18],
    "key4":[19,20,21,"ineuron","data_science",24]
} 

In [17]:
df11 = pd.DataFrame(d11)
df12 = pd.DataFrame(d12)

In [18]:
df11

a   b   c   d
0       1   7  13  19
1       2   8  14  20
2       3   9  15  21
3       4  10  16  22
4       5  11  17  23
5  bhumik  12  18  24

In [19]:
df12

key1   key2  key3          key4
0       1      7    13            19
1       2      8    14            20
2       3  sawde    15            21
3       4     10    16       ineuron
4       5     11    17  data_science
5  bhumik     12    18            24

In [20]:
pd.merge(df11,df12,how = "left", left_on = "a", right_on = "key1")

a   b   c   d    key1   key2  key3          key4
0       1   7  13  19       1      7    13            19
1       2   8  14  20       2      8    14            20
2       3   9  15  21       3  sawde    15            21
3       4  10  16  22       4     10    16       ineuron
4       5  11  17  23       5     11    17  data_science
5  bhumik  12  18  24  bhumik     12    18            24

In [21]:
## Join Operation
d10 = {
    "key11":[1,2,3,4,5,"bhumik"],
    "key21":[7,8,9,10,11,12],
    "key31":[13,14,15,16,17,18],
    "key41":[19,20,21,22,23,24]
} 

In [22]:
d20 = {
    "key1":[1,2,3,4,5,"bhumik"],
    "key2":[7,8,"sawde",10,11,12],
    "key3":[13,14,15,16,17,18],
    "key4":[19,20,21,"ineuron","data_science",24]
} 

In [23]:
df10 = pd.DataFrame(d10,index = [1,2,3,4,5,6])
df20 = pd.DataFrame(d20,index = [1,2,3,4,5,"bhumik"])

In [24]:
df10

key11  key21  key31  key41
1       1      7     13     19
2       2      8     14     20
3       3      9     15     21
4       4     10     16     22
5       5     11     17     23
6  bhumik     12     18     24

In [25]:
df20

key1   key2  key3          key4
1            1      7    13            19
2            2      8    14            20
3            3  sawde    15            21
4            4     10    16       ineuron
5            5     11    17  data_science
bhumik  bhumik     12    18            24

In [26]:
df10.join(df20) # by default join takes left

key11  key21  key31  key41 key1   key2  key3          key4
1       1      7     13     19    1      7  13.0            19
2       2      8     14     20    2      8  14.0            20
3       3      9     15     21    3  sawde  15.0            21
4       4     10     16     22    4     10  16.0       ineuron
5       5     11     17     23    5     11  17.0  data_science
6  bhumik     12     18     24  NaN    NaN   NaN           NaN

In [27]:
df10.join(df20,how = "outer")

key11  key21  key31  key41    key1   key2  key3          key4
1            1    7.0   13.0   19.0       1      7  13.0            19
2            2    8.0   14.0   20.0       2      8  14.0            20
3            3    9.0   15.0   21.0       3  sawde  15.0            21
4            4   10.0   16.0   22.0       4     10  16.0       ineuron
5            5   11.0   17.0   23.0       5     11  17.0  data_science
6       bhumik   12.0   18.0   24.0     NaN    NaN   NaN           NaN
bhumik     NaN    NaN    NaN    NaN  bhumik     12  18.0            24

In [28]:
df10.join(df20,how = "right")

key11  key21  key31  key41    key1   key2  key3          key4
1          1    7.0   13.0   19.0       1      7    13            19
2          2    8.0   14.0   20.0       2      8    14            20
3          3    9.0   15.0   21.0       3  sawde    15            21
4          4   10.0   16.0   22.0       4     10    16       ineuron
5          5   11.0   17.0   23.0       5     11    17  data_science
bhumik   NaN    NaN    NaN    NaN  bhumik     12    18            24

In [29]:
# df10.join(df20,how = "left")

In [30]:
df10.join(df20,how = "inner")  #common

key11  key21  key31  key41 key1   key2  key3          key4
1     1      7     13     19    1      7    13            19
2     2      8     14     20    2      8    14            20
3     3      9     15     21    3  sawde    15            21
4     4     10     16     22    4     10    16       ineuron
5     5     11     17     23    5     11    17  data_science

    difference between join and merge:
    join matches the indexes while merge check for column values

In [32]:
pd.concat([df10,df20], axis = 0) # row wise concatenation

key11  key21  key31  key41    key1   key2  key3          key4
1            1    7.0   13.0   19.0     NaN    NaN   NaN           NaN
2            2    8.0   14.0   20.0     NaN    NaN   NaN           NaN
3            3    9.0   15.0   21.0     NaN    NaN   NaN           NaN
4            4   10.0   16.0   22.0     NaN    NaN   NaN           NaN
5            5   11.0   17.0   23.0     NaN    NaN   NaN           NaN
6       bhumik   12.0   18.0   24.0     NaN    NaN   NaN           NaN
1          NaN    NaN    NaN    NaN       1      7  13.0            19
2          NaN    NaN    NaN    NaN       2      8  14.0            20
3          NaN    NaN    NaN    NaN       3  sawde  15.0            21
4          NaN    NaN    NaN    NaN       4     10  16.0       ineuron
5          NaN    NaN    NaN    NaN       5     11  17.0  data_science
bhumik     NaN    NaN    NaN    NaN  bhumik     12  18.0            24

In [33]:
pd.concat([df1,df2], axis = 0)

key1   key2  key3          key4
0       1      7    13            19
1       2      8    14            20
2       3      9    15            21
3       4     10    16            22
4       5     11    17            23
5  bhumik     12    18            24
0       1      7    13            19
1       2      8    14            20
2       3  sawde    15            21
3       4     10    16       ineuron
4       5     11    17  data_science
5  bhumik     12    18            24

In [34]:
pd.concat([df1,df2], axis = 1)

key1 key2  key3 key4    key1   key2  key3          key4
0       1    7    13   19       1      7    13            19
1       2    8    14   20       2      8    14            20
2       3    9    15   21       3  sawde    15            21
3       4   10    16   22       4     10    16       ineuron
4       5   11    17   23       5     11    17  data_science
5  bhumik   12    18   24  bhumik     12    18            24

In [35]:
pd.concat([df10,df20], axis = 1)

key11  key21  key31  key41    key1   key2  key3          key4
1            1    7.0   13.0   19.0       1      7  13.0            19
2            2    8.0   14.0   20.0       2      8  14.0            20
3            3    9.0   15.0   21.0       3  sawde  15.0            21
4            4   10.0   16.0   22.0       4     10  16.0       ineuron
5            5   11.0   17.0   23.0       5     11  17.0  data_science
6       bhumik   12.0   18.0   24.0     NaN    NaN   NaN           NaN
bhumik     NaN    NaN    NaN    NaN  bhumik     12  18.0            24

# Numpy
    numerical python

In [36]:
import numpy as np

In [37]:
l = [1,2,3,4,5]

In [38]:
type(l)

list

In [39]:
np.array(l)

array([1, 2, 3, 4, 5])

In [40]:
a = np.array(l)

In [41]:
type(a)  # ndimensional array

numpy.ndarray

In [42]:
a1 = np.array([[1,2,3],[4,5,6]])  # should be of symmetric dimension

In [43]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
a2 = np.array([[[1,2,3],[4,.5,6]]])

In [45]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [46]:
a.ndim

1

In [47]:
a1.ndim

2

In [48]:
a2.ndim

3

In [49]:
# system understands dataframe and matrices, not even a dataframe

In [50]:
a3 = np.array([[[1,2,3],[4,.5,6]],[[1,2,3],[4,.5,6]],[[1,2,3],[4,.5,6]]])

In [51]:
a3

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [52]:
a3.ndim  # 3D - combination 2D

3

In [53]:
l = [1,2,3,4]

In [54]:
np.asarray(l)  #1D

array([1, 2, 3, 4])

In [55]:
np.matrix(l)  # 2D - matrix would be min. of atleast 2D

matrix([[1, 2, 3, 4]])

In [56]:
a = np.asarray(l)
m = np.matrix(l)

In [57]:
np.asanyarray(l)  

array([1, 2, 3, 4])

In [58]:
np.asanyarray(l)  

array([1, 2, 3, 4])

In [59]:
np.asanyarray(m)  

matrix([[1, 2, 3, 4]])

     matrix is a subclass of array, array is a super class

In [60]:
a

array([1, 2, 3, 4])

In [61]:
a1 = a 

In [62]:
a1

array([1, 2, 3, 4])

In [63]:
a[0] = 10

In [64]:
a

array([10,  2,  3,  4])

In [65]:
a1  # changes in a is reflected in a1

array([10,  2,  3,  4])

In [66]:
a2 = np.copy(a)  # deep copy

In [67]:
a2

array([10,  2,  3,  4])

In [68]:
a2[2] = 30

In [69]:
a2

array([10,  2, 30,  4])

In [70]:
a

array([10,  2,  3,  4])

In [71]:
# in this case it is not reflecting the changes from where we copied the data 

In [72]:
np.fromfunction(lambda i,j : i == j, (3,4)) # 3 row, 4 column

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [73]:
np.random.rand(2,3)

array([[0.71265922, 0.88850779, 0.89532392],
       [0.02674376, 0.23607794, 0.9983834 ]])

In [74]:
np.random.rand(2,3,2)
#          (2matrixes of 3(row)*2(col))

array([[[0.71797579, 0.54399116],
        [0.75218193, 0.78792272],
        [0.65623932, 0.34492815]],

       [[0.13785353, 0.09026305],
        [0.34878343, 0.5390407 ],
        [0.7002408 , 0.09896821]]])

In [75]:
np.random.rand(2,3,2,2)  # 4D array
    #       (   3 such array- 2*2)

array([[[[0.19064567, 0.3829302 ],
         [0.61052596, 0.57294613]],

        [[0.43983918, 0.59900587],
         [0.10856713, 0.9451137 ]],

        [[0.72555795, 0.51998547],
         [0.51172544, 0.61528824]]],


       [[[0.31368889, 0.51626327],
         [0.96791239, 0.45670087]],

        [[0.6824599 , 0.84598258],
         [0.92545654, 0.74985045]],

        [[0.39033138, 0.05155084],
         [0.53140134, 0.51627725]]]])

In [76]:
np.random.rand(1,4,4)
# 4*4 , 1 such array

array([[[0.62136964, 0.08586124, 0.27914945, 0.35711732],
        [0.39873074, 0.95858761, 0.52433953, 0.52290312],
        [0.1695586 , 0.27603026, 0.57211928, 0.82022903],
        [0.95475174, 0.03538743, 0.75494762, 0.80414752]]])

In [77]:
np.random.rand(3,4,4)

array([[[0.65806531, 0.54225123, 0.21952929, 0.44542661],
        [0.9385401 , 0.55668862, 0.92709821, 0.82269703],
        [0.70743216, 0.37415262, 0.07422212, 0.14403725],
        [0.91125345, 0.70168253, 0.71198207, 0.60924338]],

       [[0.5427338 , 0.30848415, 0.38973572, 0.53935033],
        [0.79276085, 0.56562657, 0.32755398, 0.73483609],
        [0.5439998 , 0.84549834, 0.29767235, 0.48323525],
        [0.21613399, 0.03194206, 0.37252488, 0.52579944]],

       [[0.86505932, 0.24702787, 0.19320722, 0.59438533],
        [0.61917005, 0.06041703, 0.48407269, 0.07256948],
        [0.25721774, 0.75064309, 0.60953108, 0.83834144],
        [0.24827371, 0.1533576 , 0.25701649, 0.88196141]]])

In [78]:
np.random.randn(3,4,4)  # generates data from Standard Normal Distribution (0,1)

array([[[-0.90340745, -0.26538948,  0.42926668,  0.83080558],
        [-0.86560707, -0.47465493,  0.3900622 ,  0.47112567],
        [ 1.97150689, -0.42486716,  0.19378152,  1.84705007],
        [-1.11357421,  0.43754682,  0.95856231, -0.63804399]],

       [[ 0.17331056, -0.14029442, -1.21342599,  2.37717856],
        [ 0.63136588, -1.02277725, -0.59200136,  0.22471417],
        [ 0.06272899, -2.17641881,  1.43294978, -1.14926077],
        [ 0.06481973,  0.75702865,  0.73154212, -1.96386884]],

       [[-0.7883546 ,  1.08296864, -0.34696568, -0.47929801],
        [ 1.66392507,  1.50028834, -0.47177297,  2.51443322],
        [-0.45250313,  0.646837  ,  0.00749275, -0.41572047],
        [ 0.06497789,  1.279394  , -1.16978685,  0.16387586]]])

In [79]:
np.random.randint(0,10,(4,4))  # generates data as integer
# between 0-10 of 4 * 4

array([[6, 0, 9, 6],
       [0, 6, 8, 9],
       [7, 0, 8, 3],
       [5, 0, 2, 5]])

In [80]:
np.random.randint(0,10,(4,4,2))  # 4*2, 4 such array

array([[[4, 9],
        [2, 6],
        [3, 3],
        [8, 1]],

       [[3, 8],
        [2, 4],
        [2, 9],
        [0, 6]],

       [[1, 3],
        [2, 2],
        [2, 7],
        [0, 0]],

       [[4, 7],
        [1, 9],
        [9, 1],
        [5, 5]]])

In [81]:
d = np.random.randn(3,4)


In [82]:
pd.DataFrame(d)

0         1         2         3
0  1.572768  1.924974 -0.662429 -2.158454
1  0.348147 -1.622520  0.220666 -0.101651
2  0.807398  0.156258 -0.076700  0.952773

In [83]:
d1 = np.random.randint(0,10,(4,4,2))    #4*4(2) = 32

In [84]:
d1.reshape(16,2)
# d1.reshape(8,4)

array([[3, 8],
       [8, 0],
       [9, 6],
       [1, 0],
       [0, 7],
       [9, 2],
       [3, 2],
       [1, 3],
       [9, 8],
       [9, 4],
       [4, 8],
       [2, 4],
       [4, 7],
       [5, 7],
       [5, 6],
       [4, 0]])

In [85]:
pd.DataFrame(d1.reshape(16,2))  # to convert to DataFrame it should be 2D, becz dataframe is always 2D

0  1
0   3  8
1   8  0
2   9  6
3   1  0
4   0  7
5   9  2
6   3  2
7   1  3
8   9  8
9   9  4
10  4  8
11  2  4
12  4  7
13  5  7
14  5  6
15  4  0