In [1]:
import numpy as np

In [2]:
range(10)  # generator function

range(0, 10)

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
# range takes upper bound, lower bound and jump as integer

In [5]:
# to generate a floating point no. 
np.arange(.5,10)   # excluding upper bound

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [6]:
np.arange(5,-4,-1)  # also generates data on -ve axis

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [7]:
np.arange(5,-4,-.5) 

array([ 5. ,  4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ,
       -0.5, -1. , -1.5, -2. , -2.5, -3. , -3.5])

In [8]:
# arange()   - is nothing but advance version of range function

In [9]:
np.linspace(1,5,20)   # generates 20 dataset between 1 to 5, upper and lower bound included

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [10]:
np.linspace(1,5,20,retstep = True)   # retstep - shows jump size  

(array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367)

In [11]:
np.logspace(1,50,10) # dividing the entire scale in 10 chunks based on that producing a data and taking the log of it

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((3,5,2)) 
#5*2 matrixes, 3 such matrixes  (3d ,i.e.3 different layer one after other in the z-axis in the depth of it)

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3,4,2))  # one bracket for function and another bracket for dimension

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [17]:
np.ones(5) + 5

array([6., 6., 6., 6., 6.])

In [18]:
np.ones(5) * 5

array([5., 5., 5., 5., 5.])

In [19]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.eye(4)   # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
a = np.eye(5)

In [22]:
a.shape

(5, 5)

In [23]:
a.size   # gives no. of element present

25

In [24]:
a.ndim

2

In [25]:
a1 = np.random.randn(3,4)

In [26]:
a1

array([[-0.22420066, -0.21348555,  1.40212138,  0.42308961],
       [ 0.19882444, -0.5703657 , -0.9754465 , -1.82318488],
       [-1.27324048, -2.13989328, -0.80948953, -0.85996805]])

In [27]:
a1[1][1]

-0.5703657041151824

In [28]:
a1[0:2,0:2]

array([[-0.22420066, -0.21348555],
       [ 0.19882444, -0.5703657 ]])

In [29]:
a1[[0,1],0:2]

array([[-0.22420066, -0.21348555],
       [ 0.19882444, -0.5703657 ]])

In [30]:
a1[1:3,-1:]

array([[-1.82318488],
       [-0.85996805]])

In [31]:
a1[[1,2],3]

array([-1.82318488, -0.85996805])

In [32]:
import pandas as pd 
pd.DataFrame(a1)

0         1         2         3
0 -0.224201 -0.213486  1.402121  0.423090
1  0.198824 -0.570366 -0.975446 -1.823185
2 -1.273240 -2.139893 -0.809490 -0.859968

In [33]:
import numpy as np
m1 = np.random.randint(1,3,(3,3))

In [34]:
m2 = np.random.randint(2,4,(3,3))

In [35]:
m1

array([[1, 1, 1],
       [2, 1, 2],
       [2, 1, 2]])

In [36]:
m2

array([[2, 2, 3],
       [2, 3, 3],
       [3, 2, 3]])

In [37]:
m1*m2  # not a matrix multiplication, it's an element wise multiplication

array([[2, 2, 3],
       [4, 3, 6],
       [6, 2, 6]])

In [38]:
m1@m2   # matrix multiplication

array([[ 7,  7,  9],
       [12, 11, 15],
       [12, 11, 15]])

In [39]:
# m1(n*m)  and m2(p*r)
# then m = p and result(n*r)

In [40]:
pow(m2,2)  # finds power of 2 for every elemet 

array([[4, 4, 9],
       [4, 9, 9],
       [9, 4, 9]])

In [41]:
pow(m2,4)  # finds power of 4 for every elemet 

array([[16, 16, 81],
       [16, 81, 81],
       [81, 16, 81]], dtype=int32)

In [42]:
np.sqrt(m2)

array([[1.41421356, 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 1.73205081],
       [1.73205081, 1.41421356, 1.73205081]])

In [43]:
np.log10(m2)

array([[0.30103   , 0.30103   , 0.47712125],
       [0.30103   , 0.47712125, 0.47712125],
       [0.47712125, 0.30103   , 0.47712125]])

In [44]:
np.exp(m2)

array([[ 7.3890561 ,  7.3890561 , 20.08553692],
       [ 7.3890561 , 20.08553692, 20.08553692],
       [20.08553692,  7.3890561 , 20.08553692]])